### ISSUE TITLE
Spider bricht ab: session deleted because of page crash

### ISSUE THREAD

**Issue by marians** [netzbegruenung/green-spider#116]
Der nachfolgende Fehler entsteht in `load_in_browser.check_responsiveness()` für die Site https://www.gruene-wt.de/ :

```
INFO:root:Starting job https://www.gruene-wt.de/
Traceback (most recent call last):
  File "/cli.py", line 87, in <module>
    spider.work_of_queue(datastore_client, args.kind)
  File "/spider/spider.py", line 94, in work_of_queue
    result = check_and_rate_site(entry=job)
  File "/spider/spider.py", line 49, in check_and_rate_site
    result['checks'] = checks.perform_checks(entry['url'])
  File "/checks/__init__.py", line 74, in perform_checks
    result = checker.run()
  File "/checks/load_in_browser.py", line 71, in run
    sizes = self.check_responsiveness(url)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 292, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 319, in iter
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 361, in call
    result = fn(*args, **kwargs)
  File "/checks/load_in_browser.py", line 149, in check_responsiveness
    self.driver.get(url)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 323, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=72.0.3626.121)
  (Driver info: chromedriver=72.0.3626.121,platform=Linux 4.9.0-8-amd64 x86_64)
```

**Comment by marians** [comment]
Das Problem ist mit der URL https://www.gruene-wt.de/ in der aktuellsten Spider-Version nicht mehr nachvollziehbar.
